# This workflow will upload a Python Package using Twine when a new commit
# to main is pushed
---
name: Python Continuous Deployment

on:  # yamllint disable-line rule:truthy
    push:
        branches: ["main"]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: '3.x'
            - name: Install dependencies
              run: |
                  make bootstrap

            - name: Check if version was bumped
              run: |
                  published=$(curl -s https://pypi.org/pypi/infrahouse-core/json | jq -r .info.version)
                  current=$(python -c "from infrahouse_core import __version__; print(__version__)")
                  if [[ "$published" != "$current" ]]
                  then
                    echo "PUBLISH=yes" >> $GITHUB_ENV
                  else
                    echo "PUBLISH=no" >> $GITHUB_ENV
                  fi

            - name: Build package
              if: env.PUBLISH == 'yes'
              run: |
                python -m build

            - name: Publish python package
              if: ${{ env.PUBLISH == 'yes'}}
              uses: pypa/gh-action-pypi-publish@e9ccbe5a211ba3e8363f472cae362b56b104e796
              with:
                  user: __token__
                  password: ${{ secrets.PYPI_API_TOKEN }}
